### ISSUE TITLE
Alba and Dependency Injections

### ISSUE THREAD

**Issue by alex-lairan** [okuramasafumi/alba#105]
Hi,

I would like to use Alba on my app, however I am using dependency injection to play with my controllers (thanks https://dry-rb.org/gems/dry-auto_inject/0.6/ )

This gem assumes that the serializer should know about the resources it has to serialize on the initialization phase.
This breaks the possibility to use dependency injection, and so to use the serializer as an external dependency.

There is a possibility to add a way to add thing like `serializer.serialize_ressource(user)` 

Here is an example of how I use dependency injection on a personal project (we use the same system at work) https://github.com/alex-lairan/GoldivoreBack/blob/master/src/application/controllers/raids/index.rb

**Comment by okuramasafumi** [comment]
Thanks for the idea, I'll try to introduce Alba to your example.

**Comment by okuramasafumi** [comment]
I didn't know anything about DI, but now I know a bit of it. So, it registers `MySerializer.new` automatically, but there's no argument so an error occurs.
https://github.com/okuramasafumi/GoldivoreBack/tree/introduce-alba
In the branch above, I managed to make it work with Alba. I'm new to Hanami so I put the serializer code in the container file, which should be a bad idea. Also, the form of the API is now an Array instead of a Hash, that's the current implementation for collection (I think I need to fix this for us to customize collection format).
I think Alba's design doesn't go along well with dry-auto_inject. But it's better to provide a way to use Alba in Hanami!

**Comment by wuarmin** [comment]
Hey @alex-lairan,
you could create a bootable dry-dependency, which injects all alba resource instances into your container. Then you can achieve dependency injection. If you are interested, I could show you an example of that. 

Best regards

**Comment by okuramasafumi** [comment]
@alex-lairan Hi, are you satisfied with @wuarmin 's solution? If so I'll close this issue, if not please tell us why.

**Comment by alex-lairan** [comment]
It could, but are the resources auto-loaded?

This is a pain point to add manually a class to the container each time you create another one.

**Comment by alex-lairan** [comment]
@wuarmin nice.
I will try something for my app this weekend and I will share it here.

I don't use Hanami::Utils because it uses deprecated gems.

To be sure, `Hanami::Utils.require!` is the same as `Dir[path].each { require &1 }` ?

**Comment by wuarmin** [comment]
@alex-lairan 
Yes it's the same!

**Comment by alex-lairan** [comment]
Thanks for your help, I will move my handcrafted serializers into Alba ones ;) 

Have a nice day.
