### ISSUE TITLE
Question about Resource / Serializer, can you provide some examples ?

### ISSUE THREAD

**Issue by bcotteret** [okuramasafumi/alba#28]
Hi, 
I can't figure out how to implement the serializer class
I understand the ressource, but how look like the Serializer class ?

Here is what my serializer from AMS

```ruby
class IssueSerializer < ActiveModel::Serializer  
  attributes :title, :subject, :description, :conversations, :due_at, :assigned_to
  belongs_to :company
end
```

and in controller
I would like to use with metadata pagination  [Pagy](https://ddnexus.github.io/pagy/extras/metadata)

```ruby

 class IssuesController < ApiController
    include Pagy::Backend
    after_action { pagy_headers_merge(@pagy) if @pagy }
    rescue_from Pagy::OverflowError, with: :redirect_to_last_page

    def index
      @pagy, @isssues = Issue.scope(....)
      render json: { issues: @issues, pagination: pagy_metadata( @pagy, url: true )
   end

end
```
How would you advise me using Alba in this case ?
Thanks

**Comment by okuramasafumi** [comment]
It's kind of confusing, but in Alba, `Resource` class is responsible for converting objects into a Hash, and `Serializer` is responsible for dumping actual JSON string with some modification like key and metadata.
For now, please take a look at `test` directory and there are many working examples. I'll add more examples later.

For pagination, Alba doesn't provide a support for `pagy` gem or other gems. For now, you can do something like this:

```ruby
# Assume that IssueResource includes Alba::Resource

def index
  @pagy, @issues = pagy(Issue.all)
  pagy = @pagy # This is dirty trick to pass data to `metadata` block
  pagination_metadata_method = method(:pagy_metadata)
  with = proc do
    metadata :pagination do
      pagination_metadata_method.call(pagy, {url: true})
    end
  end
  render json: IssueResource.new(@issues).serialize(with: with)
end
```

Because Alba doesn't provide support for passing extra data to `metadata` block (I'm considering what is the best way to do so), we must do some dirty stuff here.
First, `serializer` part must be defined in a `Proc`. Then, `pagy` must be present as local variable. Finally, you must use `method` method to call pagination method in `metadata` block.
I surely know that this is not how it should be, so I'll improve support for pagination soon.

**Comment by bcotteret** [comment]
Hi @okuramasafumi,
Thanks for your comments
Sure, I'll have a depper look at your examples and code
Keep the good work, Alba looks as a good fit for me
