### ISSUE TITLE
Hash keys to string in 2.0 breaking change

### ISSUE THREAD

**Issue by fosrias** [okuramasafumi/alba#303]
This method no longer returns symbols for keys as it did in 1.6.0.

https://github.com/okuramasafumi/alba/blob/v2.0.0/lib/alba/resource.rb#L233

Is this on purpose? E.g. this changes keys in `serializable_hash` to strings which is a public method and a breaking change.

Or is there some way to configure `Resource` to return keys as symbols? I don't see it.

Thanks.

**Comment by okuramasafumi** [comment]
https://github.com/okuramasafumi/alba/blob/main/CHANGELOG.md#breaking-changes
This breaking change is documented and it's on purpose. As described, if you use Rails you can use `deep_symbolize_keys`.

The change was introduced in [this commit](https://github.com/okuramasafumi/alba/commit/f18aa18c91cb1fe0d1671f0ab6fd438c32aebcec) and the reason is that we want to unify data type with JSON world where there's no Symbol.

@fosrias Do you have any reason to prefer Symbol keys over String keys? If we have some reasons we'll think about providing a way.

**Comment by fosrias** [comment]
@okuramasafumi Main issue is having to refactor symbol dependencies and tests to bump to the next version, which ripples through our codebase a bit. 

That being said, easy fix in our base resource class is:
```ruby
 def transform_key(key)
  super.to_sym
end
```

`JSON.parse` does support `symbolize_names` functionality, so may be nice to support for `serialize_hash`.  So, solution could be to add a `symbolize_names: false` argument to `#transform_keys` method that then can be specified directly.

Thanks.

**Comment by okuramasafumi** [comment]
@fosrias I see, so then the easiest solution could be adding something like `Alba.symbolize_keys = true` so that you can add one line to initializer file. Would that work for you?

**Comment by fosrias** [comment]
@okuramasafumi That would work.

**Comment by okuramasafumi** [comment]
Great, I'll add that flag.

**Comment by fosrias** [comment]
Thx.

**Comment by okuramasafumi** [comment]
I'd like to keep this open until I add the flag.
