### ISSUE TITLE
Cannot serialize instance of Hash

### ISSUE THREAD

**Issue by rainerborene** [okuramasafumi/alba#397]
## Describe the bug
`Alba.collection?` considers a `Hash` as a collection because it inherits from the `Enumerable` module.

## To Reproduce
```ruby
class Example
  include Alba::Resource

  attribute :id do |example|
    example[:id]
  end
end

# `block in <class:Example>': no implicit conversion of Symbol into Integer (TypeError)
Example.new({ id: 10 }).serializable_hash
```

## Expected behavior
I would like to override the `collection?` method to detect custom objects like `Hash`.

## Environment
- Ruby version: 3.3.0

## Additional context
Previously, I had overridden the `collection?` method in my `ApplicationResource`. However, it no longer works as expected.

```ruby
class ApplicationResource
  include Alba::Resource

  def collection?
    super && !@object.is_a?(Hash)
  end
end
```

**Comment by rainerborene** [comment]
@okuramasafumi I'm using Alba to map API responses to my database structure and vice versa.

**Comment by okuramasafumi** [comment]
@rainerborene I see. Generally speaking, a Hash is a collection, so Alba's `collection?` is correct. You currently override `collection?` for your own purpose and that's the correct way.
Although `collection?` was a private API, I understand sometimes we want to override it like this case. However, now our primary implementation of `collection?` is `Alba.collection?`, it might be a problem when we define `Alba::Resource#collection?` and override it because it could be incoherent and confusing.
It might be better for users to override `Alba.collection?` and currently it's possible with something like below:

```ruby
Alba.singleton_class.prepend(Module.new do
  def collection?(object)
    super && !object.is_a?(Hash)
  end
end)
```

I know it's a bit tricky, but it works. How about this solution?

**Comment by rainerborene** [comment]
Understood. Extracting `collection?` from the `Resource` class sounds like a logical step. Monkey patching may not be the ideal solution, but it serves the purpose for now. Thank you!

**Comment by okuramasafumi** [comment]
@rainerborene #416 seems a similar issue, and I. decided to implement Hash serialization. I hope that will resolve your issue completely!
